import { Link } from '../context/RouterContext';
import { Breadcrumbs } from '../components/Breadcrumbs';
import { SeoHead } from '../components/SeoHead';

export function TermsPage() {
  const breadcrumbs = [{ label: 'Terms of Service' }];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      <SeoHead
        title="Terms of Service – CREATORCALC"
        description="Read the CREATORCALC Terms of Service, including important disclaimer information regarding estimates, earnings, and financial guidance."
        canonical="https://creatorcalc.com/terms"
        breadcrumbs={breadcrumbs}
      />

      <Breadcrumbs items={breadcrumbs} />

      <div className="mb-8">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-[#F5F7FA] tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-xs text-slate-500 dark:text-[#A7B0BC]">
          Effective Date: January 1, 2026 • Last Updated: September 2026
        </p>
      </div>

      <div className="space-y-6 text-xs sm:text-sm text-slate-600 dark:text-[#A7B0BC] leading-relaxed">
        <div className="p-6 rounded-2xl bg-white dark:bg-[#12161B] border border-slate-200 dark:border-[#252B33]">
          <h2 className="text-base font-bold text-slate-900 dark:text-[#F5F7FA] mb-2">1. Informational &amp; Estimation Disclaimer</h2>
          <p>
            All tools, formulas, figures, and calculators provided on CREATORCALC are intended strictly for educational, informational, and preliminary planning purposes.
          </p>
          <div className="mt-3 p-3.5 rounded-xl bg-amber-50 dark:bg-[#181D23] border border-amber-200 dark:border-amber-500/30 text-amber-900 dark:text-amber-300/90 text-xs leading-relaxed">
            Calculator results are estimates for informational and planning purposes only. Actual earnings, rates, and performance can vary based on platform policies, audience demographics, viewer geography, monetization eligibility, advertiser demand, market conditions, and individual commercial contract terms.
          </div>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-[#12161B] border border-slate-200 dark:border-[#252B33]">
          <h2 className="text-base font-bold text-slate-900 dark:text-[#F5F7FA] mb-2">2. No Financial, Legal, or Professional Advice</h2>
          <p>
            CREATORCALC does not offer certified tax, legal, investment, or accounting advice. Using our calculators does not constitute a fiduciary or advisory relationship. Before entering into commercial sponsorship agreements, signing talent agency representations, or filing business taxes, consult licensed accounting and legal professionals.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-[#12161B] border border-slate-200 dark:border-[#252B33]">
          <h2 className="text-base font-bold text-slate-900 dark:text-[#F5F7FA] mb-2">3. Intellectual Property &amp; Acceptable Use</h2>
          <p>
            You are granted a non-exclusive license to use the calculators for personal and commercial planning. You may freely quote, share, and screenshot calculator outputs for media kits, pitch decks, blog posts, and educational guides. You may not scrape, mirror, or repackage CREATORCALC’s proprietary codebase as a competing commercial tool without written consent.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-[#12161B] border border-slate-200 dark:border-[#252B33]">
          <h2 className="text-base font-bold text-slate-900 dark:text-[#F5F7FA] mb-2">4. Platform Independence</h2>
          <p>
            CREATORCALC is an independent utility platform. We are not endorsed, affiliated, associated, authorized, or sponsored by YouTube, Google LLC, TikTok, ByteDance Ltd, Instagram, or Meta Platforms, Inc. All platform names and trademarks are the property of their respective owners.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white dark:bg-[#12161B] border border-slate-200 dark:border-[#252B33]">
          <h2 className="text-base font-bold text-slate-900 dark:text-[#F5F7FA] mb-2">5. Limitation of Liability</h2>
          <p>
            CREATORCALC provides its software &ldquo;as is&rdquo; without warranties of any kind. Under no circumstances will CREATORCALC or its operators be liable for any lost profits, commercial disputes, or consequential damages resulting from your reliance on numbers generated by our calculators.
          </p>
        </div>

        <div className="pt-4 border-t border-slate-200 dark:border-[#252B33] flex items-center justify-between text-xs">
          <span className="text-slate-500 dark:text-[#A7B0BC]">Questions regarding these terms?</span>
          <Link href="/about" className="font-semibold text-[#7C5CFC] hover:text-[#6847F5]">
            Contact / About Information
          </Link>
        </div>
      </div>
    </div>
  );
}
